### ISSUE TITLE
Incorrect graph

### ISSUE THREAD

**Issue by fantaclaus** [crubier/code-to-graph#7]
When I try this code:

```javascript
function f()
{
    if (c1)
    {
        x = 1
    }
    else if (c2) 
    {
        z = 1
    }
}
```

I see this graph:

![image](https://user-images.githubusercontent.com/7231941/52181775-d0d44d80-2806-11e9-8ecc-8d7bfa7cf179.png)

There is no `false` branch for `if c2` condition.

If I just add `return` at the end of the function the graph becomes correct.

```javascript
function f() {
    if (c1) {
        x = 1
    }
    else if (c2) 
    {
        z = 1
    }
    return
}
```
![image](https://user-images.githubusercontent.com/7231941/52181853-b64ea400-2807-11e9-990b-44227a76960d.png)

But still there is no `false` label.

**Comment by crubier** [comment]
This is not a bug but a feature.

The goal of this package is to help reviewing code, so the resulting graph is as close from code as possible. So I am not sure if we should add the implicit `return` statement at the end of the function.

What is your opinion on this?

**Comment by fantaclaus** [comment]
For me it is just unusual to see that `if` clause has no `else` branch, because I know that for the execution flow it always exists. But OK, let it be like this.

**Comment by crubier** [comment]
I agree with your point. It depends on what we want to represent: the execution flow, or the code itself. 

I agree both are interesting. We should probably put an option for this. 

However I think representing the execution flow in many cases is more complicated than this simple case with the if.
